services:
  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    ports:
      - "8181:8181"
    volumes:
      - ./rules:/policies
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "/policies"
    restart: unless-stopped